server/spoilr/logs/urls.py
from django.urls import path

from . import views

app_name = "spoilr.logs"
urlpatterns = [
    path("", views.system_log_view, name="system"),
    path("csv/", views.system_log_csv_export, name="system_csv"),
    path("hints/", views.hint_log_view, name="hints_default_limit"),
    path("hints/<int:limit>", views.hint_log_view, name="hints"),
]

server/tph/urls.py
from collections.abc import Callable, Mapping

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView

from puzzles.views import auth, hunt, interactions, puzzles, stats, story, team, views
from puzzles.views.puzzles import (
    a_trip_down_memory_lane,
    connecting_connections,
    do_you_like_wordle,
    enneagram,
    infinity_book,
    mandalay_bay,
    marathon_block_pushing_game,
    schrodingers_maze,
    sumantle,
    temporary_name,
    triangles,
    von_schweetzs_big_question,
)

# A map from slug to list of endpoint tuples (endpoint url, API handler)
PUZZLE_SPECIFIC_ENDPOINTS: Mapping[str, list[tuple[str, Callable]]] = {
    "a-trip-down-memory-lane": [
        ("found-pin-location", a_trip_down_memory_lane.found_pin_location),
    ],
    "connecting-connections": [
        ("guess", connecting_connections.make_guess),
    ],
    "do-you-like-wordle": [
        ("newgame", do_you_like_wordle.new_game),
        ("makeguess", do_you_like_wordle.make_guess),
    ],
    "enneagram": [
        ("guess", enneagram.make_guess),
    ],
    "mandalay-bay": [
        ("spin", mandalay_bay.spin_handler),
    ],
    "marathon-block-pushing-game": [
        ("sokoban", marathon_block_pushing_game.check_sokoban),
    ],
    "schrodingers-maze": [
        ("guess", schrodingers_maze.make_guess),
    ],
    "sumantle": [
        ("guess", sumantle.make_guess),
    ],
    "temporary-name": [
        ("guess", temporary_name.make_guess),
    ],
    "triangles": [
        ("click", triangles.click),
    ],
    "von-schweetzs-big-question": [
        ("table_guess", von_schweetzs_big_question.make_guess),
        ("racer_guess", von_schweetzs_big_question.racer_guess),
    ],
}

urlpatterns = list(
    filter(
        None,
        [
            not settings.IS_PYODIDE and path("", include("django_prometheus.urls")),
            not settings.IS_PYODIDE
            and re_path(r"^impersonate/", include("impersonate.urls")),
            # urls for password reset: request_reset, validate_token, and reset_password
            path("api/", include("pwreset.urls")),
            # Puzzle-specific endpoints
            *[
                path(f"api/puzzle/{slug}/{endpoint_url}", api_handler, {"slug": slug})
                for slug, endpoints in PUZZLE_SPECIFIC_ENDPOINTS.items()
                for endpoint_url, api_handler in endpoints
            ],
            path("api/infinity-book/encode", infinity_book.encode),
            path("api/infinity-book/page", infinity_book.get_page),
            path("api/events", hunt.get_events),
            path("api/unlock_everything", team.unlock_everything),
            path("api/hunt_info", views.get_hunt_info),
            path("api/hunt_site", views.get_hunt_site),
            path("api/login", auth.log_in),
            path("api/logout", auth.log_out),
            # TODO: This can be deduped into a single endpoint for creating/reading/updating. See auth.register_individual
            path(r"api/register", auth.register),
            not settings.IS_POSTHUNT
            and re_path(r"^api/register/(?P<slug>[^//]+)$", auth.registration),
            path("api/register_individual", auth.register_individual),
            path("api/registration_teams", team.registration_teams),
            path("api/rounds", puzzles.get_rounds),
            path("api/underworld_rounds", puzzles.underworld_rounds),
            path("api/overworld_rounds", puzzles.overworld_rounds),
            path("api/opt-into-time-unlock", puzzles.opt_into_time_unlock),
            re_path(r"^api/rounds/(?P<round_slug>[^//]+)$", puzzles.puzzles_by_round),
            path("api/puzzles", puzzles.puzzles_by_round),
            path("api/puzzle_list", puzzles.get_puzzles_team_api),
            path("api/story_state", story.update_story_state),
            re_path(r"^api/story/(?P<slug>[^//]+)$", story.story_card),
            path("api/story", story.story_cards),
            path("api/shades", story.shade_cards),
            path("api/oracle_name", story.oracle_name),
            re_path(
                r"^api/dialogue/(?P<slug>[^//]+)/status$", story.get_dialogue_status
            ),
            re_path(r"^api/dialogue/(?P<slug>[^//]+)$", story.get_dialogue),
            path("api/unsubscribe", team.unsubscribe),
            re_path(r"^api/solve/(?P<slug>[^//]+)$", puzzles.solve),
            re_path(r"^api/puzzle/(?P<slug>[^//]+)/hint$", puzzles.request_hint),
            re_path(r"^api/puzzle/(?P<slug>[^//]+)$", puzzles.puzzle_data),
            path(r"api/free_answer", puzzles.get_puzzles_for_free_answers),
            re_path(r"^api/free_answer/(?P<slug>[^//]+)$", puzzles.free_answer),
            path(r"api/free_a3_answer", puzzles.get_puzzles_for_free_a3_answers),
            re_path(r"^api/free_a3_answer/(?P<slug>[^//]+)$", puzzles.free_a3_answer),
            path(r"api/free_unlock", puzzles.get_rounds_for_free_unlock),
            re_path(r"^api/free_unlock/(?P<slug>[^//]+)$", puzzles.free_unlock),
            re_path(r"^api/stats/(?P<slug>[^//]+)$", stats.stats_public),
            re_path(r"^api/position/(?P<slug>[^//]+)$", puzzles.update_position),
            re_path(
                r"^api/interaction/(?P<slug>[^//]+)$", interactions.request_interaction
            ),
            path("api/guess_log", stats.public_activity_csv),
            path("api/server.zip", views.server_zip),
            path("api/reset_local_database", views.reset_pyodide_db),
            path("authorize", auth.authorize_view, name="authorize"),
            # special path only for Caddy to check whether the client should be allowed
            # access to the requested resource based on progression
            re_path(
                r"^check/(?P<original_path>.*)$",
                auth.check_access_allowed,
            ),
        ],
    )
)

if settings.SILK_ENABLED:
    urlpatterns.append(
        re_path(r"^internal/silk/", include("silk.urls", namespace="silk"))
    )

# serves media files in dev. Otherwise, Caddy serves them
urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

if settings.DEBUG:
    urlpatterns.append(path("robots.txt", views.robots))
else:
    handler404 = "puzzles.views.views.handler404"

urlpatterns.extend(
    [
        path("admin/", admin.site.urls),
        path("spoilr/", include("spoilr.urls")),
    ]
)

server/spoilr/core/models.py
import os
import re
from typing import TYPE_CHECKING, Any, Union

from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.db.models.functions import Lower
from django_extensions.db.fields import AutoSlugField

from spoilr.utils import generate_url

if TYPE_CHECKING:
    import puzzles.models as tph_models
    from spoilr.email.models import CannedEmail
    from spoilr.events.models import Event
    from spoilr.hints.models import Hint
    from spoilr.hq.models import Task
    from spoilr.interaction.models import TeamInteractionTask
    from spoilr.registration.models import TeamRegistrationInfo


class SlugValidator(UnicodeUsernameValidator):
    regex = r"^[\w-]*$"
    message = "Only letters, numbers, underscores, and hyphens are allowed."


### Section: Hunt solving teams and users.


class TeamType(models.TextChoices):
    # Whether the team is a team controlled by the hunt setters.
    INTERNAL = "internal", "Internal Team"

    # Whether the team is for public access.
    PUBLIC = "public", "Public Team"


class InteractionType(models.TextChoices):
    # The team is submitting extra content for a puzzle. HQ needs to grade the
    # content and respond if needed.
    # This interaction is automatically created when the team sends us an email with a
    # specific subject, with the interaction's `email_key` field.
    # NB (2023): This interaction type is unused and unimplemented, primarily because
    # we do not collect emails from all team members and we can't route an email
    # to an interaction for a team if we don't know which team the email is from.
    SUBMISSION = "submission", "Submission for puzzle"

    # The team has unlocked a story interaction. HQ needs to schedule a live
    # interaction, or send a fallback email with the interaction content.
    # This interaction is automatically created either when the team solves the
    # puzzle in the `puzzle` field.
    STORY = "story", "Story"

    # The team is requesting a physical puzzle, or access to a staffed room.
    # HQ needs to coordinate a time/location for the team to retrieve the puzzle
    # or go to the staffed room.
    PHYSICAL = "physical", "Physical"

    # The team has become eligible for automatically unlocking some hunt content.
    # HQ needs to approve giving the team access, and send an email to the
    # captain with an unlock link.
    UNLOCK = "unlock", "Unlock"

    # The team has requested a free answer for a puzzle.
    # HQ needs to contact the captain and get them to approve spending the free
    # answer token.
    ANSWER = "answer", "Answer"


class SpoilrTeamManager(models.Manager["Team"]):
    def get_queryset(self, *args: Any, **kwargs: Any):
        # Prefetches the associated hunt team automatically.
        # You may wish to delete this if you use spoilr directly.
        return super().get_queryset(*args, **kwargs).select_related("team")


class Team(models.Model):
    objects = SpoilrTeamManager()

    username = models.CharField(
        max_length=50, unique=True, validators=[SlugValidator()]
    )
    name = models.CharField(max_length=200, unique=True)
    # Public slug for use in URLs (autogenerated from name) -- not
    # necessarily the same as the username
    slug = AutoSlugField(max_length=200, unique=True, populate_from=("name",))  # type: ignore
    creation_time = models.DateTimeField(auto_now_add=True, null=True)

    rounds = models.ManyToManyField("Round", through="RoundAccess")
    puzzles = models.ManyToManyField("Puzzle", through="PuzzleAccess")
    interactions = models.ManyToManyField("Interaction", through="TeamInteraction")

    type = models.CharField(
        max_length=20, choices=TeamType.choices, null=True, blank=True
    )

    id: int
    puzzleaccess_set: models.Manager["PuzzleAccess"]
    puzzlesubmission_set: models.Manager["PuzzleSubmission"]
    roundaccess_set: models.Manager["RoundAccess"]
    teaminteraction_set: models.Manager["TeamInteraction"]
    hint_set: models.Manager["Hint"]
    user_set: models.Manager["User"]
    teamregistrationinfo: "TeamRegistrationInfo"

    # Legacy. Can't delete until the migrations are redone from scratch.
    def user_profile_filename(self, filename: str) -> str:
        _, extension = os.path.splitext(filename)
        return f"team/{self.username}/profile_picture{extension}"

    @property
    def is_internal(self) -> bool:
        return self.type == TeamType.INTERNAL

    @property
    def is_public(self) -> bool:
        return self.type == TeamType.PUBLIC

    @property
    def shared_account(self) -> Union["User", None]:
        return self.user_set.filter(team_role=UserTeamRole.SHARED_ACCOUNT).first()

    @property
    def contact_email(self) -> str | None:
        return (
            self.teamregistrationinfo.contact_email
            if hasattr(self, "teamregistrationinfo")
            else None
        )

    # The teamwide email if it exits, else the contact email
    @property
    def team_email(self) -> str:
        email = ""
        if hasattr(self, "teamregistrationinfo"):
            email = self.teamregistrationinfo.bg_emails
        return email or self.contact_email or ""

    @property
    def all_emails(self) -> list[str]:
        team_email = self.team_email
        contact_email = self.contact_email
        emails: list[str | None] = [team_email]
        if team_email != contact_email:
            emails.append(contact_email)
        return [email for email in emails if email]

    # TODO(sahil): Remove this property and work with the request.user.is_staff directly instead.
    @property
    def is_admin(self) -> bool:
        return bool(self.shared_account and self.shared_account.is_staff)

    def __str__(self) -> str:
        return self.name

    class Meta:
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_type_valid",
                check=models.Q(type__in=TeamType.values),
            ),
            models.UniqueConstraint(
                fields=["type"],
                name="%(app_label)s_%(class)s_public_unique",
                condition=models.Q(type=TeamType.PUBLIC),
            ),
            models.UniqueConstraint(
                Lower("username"),
                name="%(app_label)s_%(class)s_lowercase_username_unique",
            ),
        ]


class UserTeamRole(models.TextChoices):
    SHARED_ACCOUNT = "shared", "Shared Account"
    # Note: In future hunts, we could support each solver having their own
    # user, and it's linked to the team. That could be implemented by adding
    # more roles here, like Captain and Member, along with some team admin
    # pages to browse and add team members.


class User(AbstractUser):
    """
    Custom Django user model to use for the hunt. It includes hunt team related
    metadata.
    """

    username_validator = SlugValidator()
    username = models.CharField(
        "Username",
        max_length=150,
        unique=True,
        help_text=(
            "Required. 150 characters or fewer. Letters, numbers, underscores, and"
            " hyphens only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": "A user with that username already exists.",
        },
    )

    team = models.ForeignKey(Team, on_delete=models.PROTECT, null=True, blank=True)
    team_role = models.CharField(
        max_length=20, choices=UserTeamRole.choices, null=True, blank=True
    )

    team_id: int

    class Meta:
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_team_role_valid",
                check=models.Q(team_role__in=UserTeamRole.values),
            ),
            models.UniqueConstraint(
                fields=["team"],
                condition=models.Q(team_role=UserTeamRole.SHARED_ACCOUNT),
                name="%(app_label)s_%(class)s_unique_team_shared_account",
            ),
            models.CheckConstraint(
                check=models.Q(team__isnull=True, team_role__isnull=True)
                | models.Q(team__isnull=False, team_role__isnull=False),
                name="%(app_label)s_%(class)s_is_captain_if_team",
            ),
            models.UniqueConstraint(
                fields=["email"],
                condition=~models.Q(email__exact=""),
                name="%(app_label)s_%(class)s_unique_email_or_blank",
            ),
        ]


class UserAuth(models.Model):
    """Authentication metadata for users."""

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    token = models.CharField(max_length=128)
    create_time = models.DateTimeField(auto_now_add=True)
    delete_time = models.DateTimeField(blank=True, null=True)


### Section: Modeling the hunt.


class Round(models.Model):
    act = models.IntegerField(default=1)
    slug = models.SlugField(max_length=200, unique=True)
    name = models.CharField(max_length=200, unique=True)
    order = models.IntegerField(unique=True)
    superround = models.ForeignKey(
        "self",
        on_delete=models.PROTECT,
        related_name="subrounds",
        null=True,
        blank=True,
    )

    id: int
    tph_round: "tph_models.Round"

    def __str__(self) -> str:
        return self.name

    @property
    def site(self) -> str:
        return "hunt"

    @property
    def url(self) -> str:
        return generate_url("hunt", f"/rounds/{self.slug}")

    class Meta:
        ordering = ["order"]


class Puzzle(models.Model):
    # Deterministic ID for the puzzle, so that code and configuration can reliably
    # refer to a puzzle.
    external_id = models.IntegerField(unique=True)
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True)

server/spoilr/logs/templates/hint-log.html
{% extends "hq/layout.tmpl" %}
{% load spacelesser static %}

{% block heading %}Hint Log{% endblock %}

{% block stylesheets %}
  <style>
    td, th {
      font-size: 10px;
    }
  </style>
{% endblock %}

{% block breadcrumb %}{% endblock %}

{% block content %}

  Filter: <input id="filter">
  {% if limit %}
    <b>This is the short log</b>, for the full log see <a href="{% url 'spoilr.logs:hints_default_limit' %}">here</a>.<br>
  {% endif %}
  <script>
    const element = document.getElementById('filter');
    element.value = decodeURIComponent(location.hash.replace(/^#/, ''));
  </script>
  <table id="entries">
    <thead>
      <tr>
        <th>Time</th>
        <th>Team URL</th>
        <th>Puzzle</th>
        <th>Claimant</th>
        <th>Claim Time</th>
        <th>Question</th>
        <th>Result</th>
      </tr>
    </thead>
    {% for e in entries %}
      <tr class="entry">
        <td>{{ e.entry.create_time|date:'D H:i:s' }}</td>
        <td>{{ e.entry.team.username }}</td>
        <td>{{ e.entry.puzzle.name|safe }}</td>
        <td>{{ e.task.handler }}</td>
        <td>{{ e.task.claim_time|date:'D H:i:s' }}</td>
        <td class="text">{{ e.entry.question }}</td>
        <td class="text">{{ e.entry.result }}</td>
      </tr>
    {% endfor %}
  </table>
  <script>
    function applyFilter() {
      const re = element.value && new RegExp(element.value, 'ims');
      for (const row of document.getElementById('entries').tBodies[0].rows)
        row.style.display = (!re || re.test(row.textContent)) ? '' : 'none';
    }
    element.addEventListener('input', () => {
      history.replaceState(null, '', element.value ? '#' + element.value : '.');
      applyFilter();
    });
    if (element.value) {
      element.focus();
      applyFilter();
    }
  </script>
{% endblock %}

server/spoilr/logs/templates/log.html
{% extends "hq/layout.tmpl" %}
{% load spacelesser static %}

{% block heading %}System Event Log{% endblock %}

{% block stylesheets %}
  <style>
    td, th {
      font-size: 10px;
    }

    tr.puzzle-solved {
      background-color: #FEF2B9;
    }
    tr.metapuzzle-solved {
      background-color: #B3F1B0;
    }
  </style>
{% endblock %}

{% block breadcrumb %}{% endblock %}

{% block content %}
  <form method="get" class="filters">
    <h3>Search log</h3>
    <div class="form-row">
      <label for="id_puzzle">Puzzle</label>
      <select name="puzzle" id="id_puzzle">
        <option value=""{% if not puzzle %} selected{% endif %}>All</option>
        {% for puzzle_url in puzzles %}
          <option value="{{ puzzle_url }}"{% if puzzle == puzzle_url %} selected{% endif %}>{{ puzzle_url }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-row">
      <label for="id_team">Team</label>
      <select name="team" id="id_team">
        <option value=""{% if not team %} selected{% endif %}>All</option>
        {% for team_username in teams %}
          <option value="{{ team_username }}"{% if team == team_username %} selected{% endif %}>{{ team_username }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-row">
      <label for="id_search">Search</label>
      <input type="text" name="search" id="id_search" maxlength="100" value="{{ search }}">
    </div>

    <div class="form-row">
      <label for="id_limit">Limit</label>
      <select name="limit" id="id_limit">
        <option value="10"{% if limit == 10 %} selected{% endif %}>10</option>
        <option value="50"{% if limit == 50 %} selected{% endif %}>50</option>
        <option value="100"{% if limit == 100 %} selected{% endif %}>100</option>
        <option value="200"{% if limit == 200 %} selected{% endif %}>200</option>
        <option value="1000"{% if limit == 1000 %} selected{% endif %}>1000</option>
      </select>
    </div>

    <div class="form-row">
      <input type="submit" value="Update">
    </div>
  </form>

  <table id="entries">
    <thead>
      <tr>
        <th>Time</th>
        <th>Team URL</th>
        <th width="50%">Message</th>
        <th>Event Type</th>
        <th>Object ID</th>
      </tr>
    </thead>
    {% for e in entries %}
      <tr class="entry {{ e.event_type }}">
        <td>{{ e.timestamp|date:'D H:i:s' }}</td>
        <td>{% if e.team %}{{ e.team.username }}{% endif %}</td>
        <td>{{ e.message|safe }}</td>
        <td>{{ e.event_type }}</td>
        <td>{{ e.object_id }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}